name: Update Version
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update version and timestamp
        run: |
          # Получаем текущую дату в правильном формате
          NOW=$(date +'%m\/%d\/%Y %H:%M:%S')
          
          # Обновляем версию
          CURRENT_VER=$(grep -oP "const SITE_VERSION = '\K[^']+" version-updater.js)
          NEW_VER=$(echo $CURRENT_VER | awk -F. '{$NF+=1; print $0}' | tr ' ' '.')
          
          # Обновляем файл (используем разные разделители для sed)
          sed -i \
            -e "s|const SITE_VERSION = '.*'|const SITE_VERSION = '$NEW_VER'|" \
            -e "s|const LAST_UPDATED = '.*'|const LAST_UPDATED = '$NOW'|" \
            version-updater.js
          
          # Коммитим и пушим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version-updater.js
          git commit -m "Auto-update version to $NEW_VER [skip ci]"
          git push
