name: Update Version
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update version
        run: |
          # 1. Получаем текущую версию
          CURRENT=$(grep -oP "const SITE_VERSION = '\K[^']+" version-updater.js || echo "0.1.1.0")
          
          # 2. Увеличиваем последнюю цифру (0.1.1.0 → 0.1.1.1)
          NEW=$(echo $CURRENT | awk -F. '{$NF+=1; print $0}' | tr ' ' '.')
          
          # 3. Обновляем файл
          sed -i "s/const SITE_VERSION = '.*'/const SITE_VERSION = '$NEW'/" version-updater.js
          
          # 4. Пушим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version-updater.js
          git commit -m "Auto-update version to $NEW [skip ci]"
          git push origin HEAD:main
