name: Update Version
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Ключевая строка!
      
      - name: Update version
        run: |
          # 1. Получаем текущую версию
          CURRENT=$(grep -oP "version = localStorage\.getItem\('tarot-version'\) \|\| '\K[^']+" version-updater.js || echo "0.1.1.0")
          
          # 2. Увеличиваем версию
          NEW=$(echo $CURRENT | awk -F. '{$NF+=1; print $0}' | tr ' ' '.')
          
          # 3. Обновляем файл
          sed -i "s/version = localStorage\.getItem('tarot-version') || '.*'/version = localStorage\.getItem('tarot-version') || '$NEW'/" version-updater.js
          
          # 4. Пушим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version-updater.js
          git commit -m "Auto-update version to $NEW [skip ci]"
          git push origin HEAD:main
