name: Update Version
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update version in version-tracker.js
        run: |
          # 1. Получаем текущую версию из файла (или 0.1.1.0 по умолчанию)
          CURRENT=$(grep -oP "version = localStorage\.getItem\('tarot-version'\) \|\| '\K[^']+" version-tracker.js || echo "0.1.1.0")
          
          # 2. Увеличиваем последнюю цифру (0.1.1.0 → 0.1.1.1)
          NEW=$(echo $CURRENT | awk -F. '{$NF+=1; print $0}' | tr ' ' '.')
          
          # 3. Обновляем файл version-tracker.js
          sed -i "s/version = localStorage\.getItem('tarot-version') || '.*'/version = localStorage\.getItem('tarot-version') || '$NEW'/" version-tracker.js
          
          # 4. Пушим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version-tracker.js
          git commit -m "Auto-update version to $NEW [skip ci]"
          git push
